### ISSUE TITLE
[BUG] No option to add video in Load Video Node

### ISSUE THREAD

**Issue by devildriverz** [Nuked88/ComfyUI-N-Nodes#39] opened 2024-02-25 20:13 UTC
**No option to add video**

**Screenshots**
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/39323876/40b747b0-1ae7-439d-ac8d-a3a4045fc3ef)

**Comment by Nuked88** [comment] 2024-02-26 06:41
Hi, log please!

**Comment by devildriverz** [comment] 2024-02-26 13:06
@Nuked88 Tried reinstalling, no error in the dependencies. It was successfully installed. But still, the node has no button to select/upload video. Is there any additional installation step apart from the ComfyUI Manager?

**Comment by Nuked88** [comment] 2024-02-26 14:18
Hi! For some reason is not installing Timm, I need to reproduce the problem and then i'll let you know!

**Comment by devildriverz** [comment] 2024-02-27 00:00
@Nuked88 I tried adding it to one of the requirement.txt and installing it. It's present in site-packages too but still its throwing same error.

**Comment by damagedcase1969** [comment] 2024-02-27 00:56
Hi, I'm having the same problem

**Comment by Nuked88** [comment] 2024-02-27 13:56
can you guys give me the list of all the custom node you have installed? I suspect that some other node is in conflict with mine

**Comment by somenewaccountthen** [comment] 2024-02-27 14:51
I have;
ComfyUI-Manager
ComfyUI-N-Nodes
comfyui_controlnet_aux

I am running in venv, i installed the requirements.txt of  ComfyUI-N-Nodes and comfyui_controlnet_aux manually into venv.

**Log**

** ComfyUI start up time: 2024-02-27 15:43:48.427001

Prestartup times for custom nodes:
   0.0 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11009 MB, total RAM 48088 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Current version of packaging: 23.2
Version of cpuinfo: Version information not found
Current version of git: 3.1.42
Current version of moviepy: 1.0.3
Current version of cv2: 4.9.0
Current version of skbuild: 0.17.6
Version of typing: Version information not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu121
Current version of timm: 0.9.16
timm is already up-to-date with version 0.9.16
### Loading: ComfyUI-Manager (V1.5.2)
### ComfyUI Revision: 2025 [1e0fcc9a] | Released on '2024-02-27'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']

Import times for custom nodes:
   0.0 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.7 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-N-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

Stopped server


--------------
No errors in browser F12 screen. 
Firefox. Linux.
Same issue of no upload/video window as mentioned in OP.

What package/node is responsible for showing that 'control'?

**Comment by Nuked88** [comment] 2024-02-27 15:10
> Requirement already satisfied: timm in c:\users\kaila\appdata\roaming\python\python311\site-packages (0.9.16)

You know what's weird in this log?
This line:
Requirement already satisfied: timm in c:\users\kaila\appdata\roaming\python\python311\site-packages (0.9.16)
Why is the portable enviroment searching in your global enviroment? This is not happening to me even if i have the same enviroment as you! This is leading ComfyUI thinking that you have timm already installed in the portable enviroment but in reality is not. You can easily solve the problem by temporarily remove timm from your global enviroment and launching comfyui so timm should be correctly installed. (Then you can reinstall it in the global enviroment)
Btw this is really really weird because ComfyUI should't check in the global enviroment, maybe you have some custom node that is adding this "feature"?

**Comment by Nuked88** [comment] 2024-02-27 15:14
> I have; ComfyUI-Manager ComfyUI-N-Nodes comfyui_controlnet_aux
> 
> I am running in venv, i installed the requirements.txt of ComfyUI-N-Nodes and comfyui_controlnet_aux manually into venv.
> 
> **Log**
> 
> ** ComfyUI start up time: 2024-02-27 15:43:48.427001
> 
> Prestartup times for custom nodes: 0.0 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-Manager
> 
> Total VRAM 11009 MB, total RAM 48088 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync VAE dtype: torch.float32 Using pytorch cross attention Current version of packaging: 23.2 Version of cpuinfo: Version information not found Current version of git: 3.1.42 Current version of moviepy: 1.0.3 Current version of cv2: 4.9.0 Current version of skbuild: 0.17.6 Version of typing: Version information not found Current version of diskcache: 5.6.3 Current version of llama_cpp: 0.2.26+cu121 Current version of timm: 0.9.16 timm is already up-to-date with version 0.9.16
> 
> ### Loading: ComfyUI-Manager (V1.5.2)
> ### ComfyUI Revision: 2025 [1e0fcc9a] | Released on '2024-02-27'
> [comfyui_controlnet_aux] | INFO -> Using ckpts path: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts [comfyui_controlnet_aux] | INFO -> Using symlinks: False [comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
> 
> Import times for custom nodes: 0.0 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-Manager 0.3 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/comfyui_controlnet_aux 0.7 seconds: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-N-Nodes
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188 FETCH DATA from: /my_dev/big_ai_etc/imaging/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
> 
> Stopped server
> 
> No errors in browser F12 screen. Firefox. Linux. Same issue of no upload/video window as mentioned in OP.
> 
> What package/node is responsible for showing that 'control'?

is a [JS](https://github.com/Nuked88/ComfyUI-N-Nodes/blob/main/js/videoLoadAdvanced.js) ,but since you have only three node maybe is just a cache issues, had you already installed my node before this update?

**Comment by somenewaccountthen** [comment] 2024-02-27 15:19
namespace?

**Comment by Nuked88** [comment] 2024-02-27 16:10
The last version of comfyui "dropped" the support"  to the way i was using to load the JS... 
I didn't know that since it was working fine a week ago...

**Comment by Nuked88** [comment] 2024-02-27 16:17
Ok i've pushed a fix, can you try now?

**Comment by damagedcase1969** [comment] 2024-02-27 16:58
> Ok i've pushed a fix, can you try now?

I updated, now I have the upload video, and it seems ok, doing a test video... at the end I'll let you know, Thank You!

**Comment by Nuked88** [comment] 2024-02-27 18:03
Perfect!

**Comment by somenewaccountthen** [comment] 2024-02-27 18:08
Works for me.
Thank you.

**Comment by damagedcase1969** [comment] 2024-02-27 19:19
Yes it works, thank you.

**Closed** 2024-03-02 10:02 UTC
Labels: bug
